# Read database records into pandas dataFrame and write it back

This will cover:
- pd.read_sql_table
- pd.read_sql_query
- df.to_sql
- pd.read_sql (which is just a wrapper for the first two methods)

## Create the table by using PGAdmin

The reason I am using posgreSql because I am familiar with it since I mostly work with PostgreSQL when working in Django and FastAPI. You are Free to use any database of your choose the steps are the same only some of the implementation will change if you choose to use a non-relational database example : MongoDB. 
Libraries that I had to install : 
1. psycopg
2. SQLAlchemy (manage database connections)
3. python-decouple (To get the database creds from .env file)
4. Pydantic (You can skip it if you don't want to write type safe functions) 
<br>

```
-- Create a customers table
CREATE TABLE Customers (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
phone_number VARCHAR(10) 
);

-- Insert data into the customers table
INSERT INTO Customers (name,phone_number) VALUES
('Rollex', '9972688590'),
('Ballistic', '1000688590'),
('Barricade', '2472688590'),
('Bullet', '7622688590'),
('Barbatos', '1172688590'),
('Artillery', '1502688590'),
('Shotgun', '1852688590'),
('Kombat', '3652688590'),
('Lockdown', '1442688590'),
('Ignition', '6000688590'),
('Shockwave', '3602688590'),
('PointBreak', '7472688590'),
('GroundZero', '8002688590'),
('Interceptor','9112688590');

-- check if the data has been successfully inserted into the customers table
SELECT * FROM Customers;

-- Create an orders table
CREATE TABLE Orders (
id BIGSERIAL PRIMARY KEY,
customer_id BIGINT NOT NULL,
name VARCHAR(255) NOT NULL,
amount MONEY NOT NULL,
order_date TIMESTAMP DEFAULT NOW(),
CONSTRAINT fk_customer FOREIGN KEY (customer_id)
REFERENCES Customers (id)
ON DELETE CASCADE
);

-- insert the data into the orders table
INSERT INTO Orders (customer_id,name,amount) VALUES
(1,'50 calibure fully automatic Browning machine gun',9978.123),
(2,'50 calibure desert eagle handgun',1000.123),
(3,'500 S and W Magnum',2470.123),
(4,'Anzio 20mm anti material sniper rifle',7620.123),
(5,'Beretta m9 9mm',1170.123),
(6,'Milkor MGL (40mm Multiple Grenade Launcher)',1500.123),
(7,'Benelli M4 (M1014) 12 gauge shotgun shell',1850.123),
(8,'AK-47',3650.123),
(9,'M249 SAW Mk 48 Mod 1 7.62×51mm',3650.123),
(10,'Javelin rocket launcher',6000.123),
(11,'Milkor MGL (40mm Multiple Grenade Launcher)',3600.123),
(12,'FN SCAR-H (Special Operations Forces Combat Assault Rifle - Heavy)',7470.123),
(13,'M249 SAW Mk 48 Mod 1 7.62×51mm',8000.123),
(14,'Beretta m9 9mm',9110.123);

-- check if the data is present in the orders table
SELECT * FROM Orders;
```

## Import all the necessary packages

In [1]:
from pydantic import BaseModel, Field, ValidationError
from decouple import config, Config,RepositoryEnv

from sqlalchemy import create_engine
from sqlalchemy.engine import Engine
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import itertools

# import path so that I can tell pandas where to look for env file in the file system.
from pathlib import Path

## Create a Pydantic model for database configuration

In [2]:
class DBConfig(BaseModel):
    db_name:str=Field(default=None)
    user:str=Field(default=None)
    password:str=Field(default=None)
    host:str=Field(default="localhost")
    port:str=Field(default=5432)

## Create a common function to create a database connection using sqlAlchemy database engine

In [3]:
def database_engine(config:DBConfig) -> Engine:
    engine = create_engine(
        f"postgresql+psycopg2://{config.user}:{config.password}@{config.host}:{config.port}/{config.db_name}"
    )
    return engine

## Tell pandas where to look for env file

In [4]:

env_path = Path("/home/aditya/github/Deep-learning-prerequisite/pandas/pandas_code/database_to_pandas/.env")
config = Config(RepositoryEnv(env_path))

## Change the working directory in Jupyter

In [5]:
import os
os.chdir("/home/aditya/github/Deep-learning-prerequisite/pandas/pandas_code/database_to_pandas/")

## Create db engine object

In [6]:
db_config=DBConfig(
    db_name=config("DB_NAME"),
    user=config("DB_USER"),
    password=config("DB_PASSWORD"),
    host=config("DB_HOST"),
    port=config("DB_PORT")
)
engine_obj=database_engine(db_config)
engine_obj

Engine(postgresql+psycopg2://postgres:***@localhost:5432/Pandas)

## Create a Pydantic model for reading table from database

In [7]:
class ReadDbTableModel(BaseModel):
    table_name:str=Field(default=None)
    engine:Engine

PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'sqlalchemy.engine.base.Engine'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.11/u/schema-for-unknown-type

### Analysis : 
```
PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'sqlalchemy.engine.base.Engine'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
```

<br>

This error is acutally coming from Pydantic and it's expected when I try to use arbitrary Python types (like ```sqlalchemy.engine.base.Engine```) as fields.
By default Pydantic cannot generate a schema for ```Engine``` because it's not a "standard" type, You have two ways to fix it:
### Solution:
There are two solutions to this predicament that I am in 
- Solution 1 : Use a validator or store as Any
  - If you don't care about the type checking for engine but just want Pydantic to accept it . This works but you lose "type hint" benefits.
- Solution 2 : Allow arbitary types
  - You can tell Pydantic to allow any type in the model using ```model_config```:

<br>

I went with solution 2 because I don't want to loose type hint.

In [8]:
class ReadDbTableModel(BaseModel):
    table_name:str=Field(default=None)
    engine:Engine
    model_config = {
    "arbitrary_types_allowed":True
    }

In [9]:
def read_db_table(config:ReadDbTableModel) -> pd.DataFrame:
    if not config.table_name:
        raise ValueError("Table name is required!")
    try:
        df = pd.read_sql_table(config.table_name,con=config.engine)
        return df
    except Exception as e:
        raise RuntimeError(f"Failed to read table '{config.table_name}': {e}")

### NOTICE : 
The reason I don't need to manually open or close connection here:
- ```pandas.read_sql_table()``` uses the SQLALchemy engine (```engine```)
- ```SQLAlchemy``` engines manage connection pooling automatically. When I call ```read_sql_table```:
  - It borrows a connection from the pool.
  - Executes the query.
  - Closes (releases) the connection back to the pool when done.
- So connections are managed automatically.

<br>

If I were using a raw connection (like ```psycopg2.connect()```), I'd have to open/close manually. But since I am using ```SQLAlchemy engine``` + ```pandas```, I don't need to.

## Generate a dataFrame from the sql_table from the database

### Get customers data from the database

In [10]:
config_read_customers_table = ReadDbTableModel(table_name="customers", engine=engine_obj)
customers_df = read_db_table(config_read_customers_table)
customers_df

    id         name phone_number
0    1       Rollex   9972688590
1    2    Ballistic   1000688590
2    3    Barricade   2472688590
3    4       Bullet   7622688590
4    5     Barbatos   1172688590
5    6    Artillery   1502688590
6    7      Shotgun   1852688590
7    8       Kombat   3652688590
8    9     Lockdown   1442688590
9   10     Ignition   6000688590
10  11    Shockwave   3602688590
11  12   PointBreak   7472688590
12  13   GroundZero   8002688590
13  14  Interceptor   9112688590

### Get orders data from the database

In [11]:
config_read_orders_table = ReadDbTableModel(table_name="orders", engine=engine_obj)
orders_df = read_db_table(config_read_orders_table)
orders_df

,id,customer_id,name,amount,order_date
0,1,1,50 calibure fully automatic Browning machine gun,"$9,978.12",2025-09-01 12:01:26.625465
1,2,2,50 calibure desert eagle handgun,"$1,000.12",2025-09-01 12:01:26.625465
2,3,3,500 S and W Magnum,"$2,470.12",2025-09-01 12:01:26.625465
3,4,4,Anzio 20mm anti material sniper rifle,"$7,620.12",2025-09-01 12:01:26.625465
4,5,5,Beretta m9 9mm,"$1,170.12",2025-09-01 12:01:26.625465
5,6,6,Milkor MGL (40mm Multiple Grenade Launcher),"$1,500.12",2025-09-01 12:01:26.625465
6,7,7,Benelli M4 (M1014) 12 gauge shotgun shell,"$1,850.12",2025-09-01 12:01:26.625465
7,8,8,AK-47,"$3,650.12",2025-09-01 12:01:26.625465
8,9,9,M249 SAW Mk 48 Mod 1 7.62×51mm,"$3,650.12",2025-09-01 12:01:26.625465
9,10,10,Javelin rocket launcher,"$6,000.12",2025-09-01 12:01:26.625465
10,11,11,Milkor MGL (40mm Multiple Grenade Launcher),"$3,600.12",2025-09-01 12:01:26.625465
11,12,12,FN SCAR-H (Special Operations Forces Combat As...,"$7,470.12",2025-09-01 12:01:26.625465
12,13,13,M249 SAW Mk 48 Mod 1 7.62×51mm,"$8,000.12",2025-09-01 12:01:26.625465
13,14,14,Beretta m9 9mm,"$9,110.12",2025-09-01 12:01:26.625465