# Stacking and Unstacking in pandas

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import itertools
import seaborn

df = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/stocks_to_demo_stacking.xlsx",header=[0,1])
df

  Unnamed: 0_level_0    Price                  Price to earnings ratio (P/E)  \
             Company Facebook Google Microsoft                      Facebook
0         2017-06-05      155    955        66                         37.10
1         2017-06-06      150    987        69                         36.98
2         2017-06-07      153    963        62                         36.78
3         2017-06-08      155   1000        61                         36.11
4         2017-06-09      156   1012        66                         37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

Let's say you want to analyze a stock market data, where you have two level of column headers.
- The first level is the metric that you are analyzing ```[price and (P/E)]```
- The second level is the company itself.

<br>

Now there is a way to make the second level header of the dataFrame in this case ```company``` can be transposed and make it a row using ```.stack()``` function. <br>
Similarly you can also make the first level header of the dataFrame in this case ```metrics``` can be transposed and make it a row using ```.stack()``` function.

In [3]:
df.stack()

/tmp/ipykernel_19420/3977694045.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack()

            Unnamed: 0_level_0   Price  Price to earnings ratio (P/E)
0 Company           2017-06-05     NaN                            NaN
  Facebook                 NaT   155.0                          37.10
  Google                   NaT   955.0                          32.00
  Microsoft                NaT    66.0                          30.31
1 Company           2017-06-06     NaN                            NaN
  Facebook                 NaT   150.0                          36.98
  Google                   NaT   987.0                          31.30
  Microsoft                NaT    69.0                          30.56
2 Company           2017-06-07     NaN                            NaN
  Facebook                 NaT   153.0                          36.78
  Google                   NaT   963.0                          31.70
  Microsoft                NaT    62.0                          30.46
3 Company           2017-06-08     NaN                            NaN
  Facebook                 NaT   155.0                          36.11
  Google                   NaT  1000.0                          31.20
  Microsoft                NaT    61.0                          30.11
4 Company           2017-06-09     NaN                            NaN
  Facebook                 NaT   156.0                          37.07
  Google                   NaT  1012.0                          30.00
  Microsoft                NaT    66.0                          31.00